import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#121212', 
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    containerHomeCustom: {
      width: '100%',
      alignItems: 'center',
    },
    titulo: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
      color: '#f1da77', 
    },
    formulario: {
      width: '100%', 
      maxWidth: 320, 
      height: 45,
      borderWidth: 1,
      borderColor: '#333',
      borderRadius: 8,
      marginBottom: 15,
      paddingHorizontal: 10,
      backgroundColor: '#1e1e1e', 
      color: '#fff', 
      alignSelf: 'center',
    },
  
    /* css clima ajustado para a home */
    cartaoClimaHome: {
      backgroundColor: '#1e1e1e',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      width: '100%',
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#333',
    },
    tempHome: {
      fontSize: 40,
      fontWeight: 'bold',
      color: '#f1da77',
    },
    descHome: {
      color: '#aaa',
      fontSize: 14,
      fontStyle: 'italic',
    },
  
    /* css devs */
    containerDevs: {
      flex: 1,
      backgroundColor: '#121212',
      paddingTop: 40,
      alignItems: 'center',
      paddingBottom: 40,
    },
    tituloDevs: {
      color: '#e7d27a',
      fontSize: 26,
      fontWeight: 'bold',
      marginBottom: 30,
    },
    cardsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      width: '100%',
      gap: 20,
    },
    card: {
      backgroundColor: '#000000',
      width: 180,
      padding: 20,
      borderRadius: 15,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#333',
    },
    imagem: {
      width: 90,
      height: 90,
      borderRadius: 45,
      marginBottom: 10,
      borderWidth: 2,
      borderColor: '#e7d27a',
    },
    nome: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#f1da77',
    },
    desc: {
      fontSize: 14,
      color: '#aaa', 
      textAlign: 'center',
    },
  
    /* HOME */
    scrollContentHome: {
      flexGrow: 1,
      paddingBottom: 80, // Espaço extra para conseguir rolar até o final sem cortar nada
      paddingHorizontal: 20,
      alignItems: 'center',
      paddingTop: 20,
    },
    func: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    funcE: {
      gap: 20,
      marginBottom: 20,
    },
    funcD: {
      gap: 20,
      marginBottom: 20,
      marginLeft: 20,
    },
    bt_todos: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    bt_concluidos: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    bt_prog: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    bt_hoje: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    bt_sinal: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    bt_criar: {
      backgroundColor: '#f1da77',
      width: 150,
      height: 120,
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      borderRadius: 15, 
      borderWidth: 2,
      borderColor: '#e7d27a', 
    },
    botaoDev: {
      marginTop: 20,
      marginBottom: 40,
      width: '100%',
      alignItems: 'center',
      gap: 10,
    },
    containerLista: {
      flex: 1,
      backgroundColor: '#121212',
      paddingTop: 20, 
    },
    center: {
      flex: 1,
      backgroundColor: '#121212',
      justifyContent: 'center',
      alignItems: 'center',
    },
    tituloTodos: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
      width: '100%',
      textAlign: 'center',
      color: '#f1da77', 
    },
    item: {
      backgroundColor: '#1e1e1e', 
      padding: 15,
      marginVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#333',
      width: '100%',
    },
    descrTarefa: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#fff', 
    },
    Conclusao: {
      fontSize: 14,
      color: '#aaa', 
    },
    tempo: {
      fontSize: 14,
      color: '#aaa',
    },
    status: {
      fontWeight: 'bold',
      marginTop: 5,
      color: '#ff6b6b', 
    },
    relevancia: {
      fontSize: 12,
      fontStyle: 'italic',
      color: '#888',
    },
    botaoPadraoCustom: {
      backgroundColor: '#f1da77',
      height: 50,
      width: '100%', 
      maxWidth: 320,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      borderWidth: 2,
      borderColor: '#e7d27a',
      alignSelf: 'center', 
    },
    textoBotaoPadrao: {
      color: '#000', 
      fontWeight: 'bold',
      fontSize: 16,
    },
    textoBotaoHome: {
      color: '#000',
      fontWeight: 'bold',
      fontSize: 16,
      margin: 12,
    },
    erro: {
      color: 'red',
      textAlign: 'center',
      marginBottom: 10,
    },
    tituloApresentar: {
      color: 'white',
    },
    cardApresentar: {
      backgroundColor: '#e7d27a',
      borderRadius: 20,
      width: 200,
      margin: 10,
      alignItems: 'center',
    },
    cardApresentarTarefas: {
      backgroundColor: '#e7d27a',
      borderRadius: 20,
      width: '100%',
      maxWidth: 350,
      marginVertical: 10,
      padding: 15,
      alignItems: 'center',
      alignSelf: 'center',
    },
    tituloTarefas: {
      margin: 20,
      color: 'white',
    },

  linkCadastro: {
  marginTop: 20,
  textAlign: 'center',
  color: 'white',
},

textoLinkCadastro: {
  color: 'blue',
  textDecorationLine: 'underline',
},
  });

export {styles}